Added unit test for the API endpoints
Daniel-olaO/nasa-APOD pull request #21
Opened 2023-04-12 22:32 UTC by Daniel-olaO

2023-04-13 17:39 UTC, Russell-Pollari requested changes
Looks good. Did not test locally though. 

Just have one quick question

2023-04-13 17:39 UTC, Russell-Pollari commented on api/views.py
> +                media_url=data['url']
Was this the fix for the image size?

2023-04-13 17:39 UTC, Russell-Pollari commented on api/tests.py
> +class UserTests(APITestCase):
cool!

2023-04-13 17:41 UTC, Daniel-olaO commented on api/views.py
> +                media_url=data['url']
Yep

2023-04-17 20:52 UTC, Russell-Pollari approved these changes
Next time, the fix for the image bug should be in a separate PR with an appropriate title. I had to guess at the line

2023-04-17 21:05 UTC, merged